### ISSUE TITLE
Content from _nuxt folder is not being reached

### ISSUE THREAD

**Issue by MaickellVilela** [lucpotage/nuxt-github-pages#1]
First of all, congratulations. This is a fantastic project.

I've followed your instructions, and I was able to host my Nuxt 3 site on GitHub Pages. However, all my CSS, images, and js weren't loaded.

Then I inspected your example, hoping to find a solution to my problem, but I noticed that you aren't loading any content from the ```_nuxt``` folder. Are we missing any configuration?

<img width="783" alt="Screenshot 2023-01-26 at 02 59 10" src="https://user-images.githubusercontent.com/7198837/214768387-be611de8-0a6f-4120-bf01-6bfa5374ada9.png">

My repository name is "portfolio". This is my nuxt.config.ts
``` javascript
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss', '@vueuse/nuxt'],
  ssr: false,
  router: {
    base: '/portfolio/', // base: '/<repository>/'
  }
})
```

I've tried to force the URL like this:
Generated:
```https://maickellvilela.github.io/_nuxt/entry.9a032aed.js``` doesn't work.

Forced:
```https://maickellvilela.github.io/portfolio/_nuxt/entry.9a032aed.js``` doesn't work either.

I would appreciate if you could help to solve this.

Thanks.

**Comment by lucpotage** [comment]
Hi @MaickellVilela, sorry for the late reply. You’re right, the config was not good at all… I wrongly assumed that [Nuxt 2 docs about GitHub deployment](https://nuxtjs.org/deployments/github-pages) were valid for Nuxt 3.

I have found another config option that makes it work. 🥳 You must define `app.baseURL` instead of `router.base`.

Hope this helps!

**Comment by MaickellVilela** [comment]
Hi @lucpotage I Appreciate your response, but it has not solved the problem.
Now the URL is correct, but there is something else interfering with the source loading.

That is why I'm asking for your help again.

The image example that you used was loaded, but the other sources haven't. Could you help me to understand why?

Maybe it could be something with the GitHub config. On your project and mine, we are having the same warning message:
⚠️ `Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.`

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy)

<img width="767" alt="Screenshot 2023-02-03 at 01 32 08" src="https://user-images.githubusercontent.com/7198837/216513028-47a27cb9-a16c-4deb-9f1a-c093c43277b4.png">

The `_payload` and `entry` files are very important for the application.

<img width="766" alt="Screenshot 2023-02-03 at 01 28 44" src="https://user-images.githubusercontent.com/7198837/216512673-2f2bceef-e946-4243-a8c9-37c2e1147bee.png">

I'm relying on you because I don't have any clue how to solve this. I really appreciate it if you can help to make the deployment of nuxt projects to GitHub effortless.

P.S.: I've deleted the node modules folder, installed all the dependencies again, build and deployed several times, and I'm having the same problem.

**Comment by lucpotage** [comment]
After trials and errors, I’ve found the solution. A `.nojekyll` file is required and was missing at the root of the published directory: https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

Regarding the warning, I’m afraid, there is nothing to do, but it’s unrelated to the previous issue: https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/
