### ISSUE TITLE
404 errors on _payload.js, entry.js...

### ISSUE THREAD

**Issue by SMNaik123** [lucpotage/nuxt-github-pages#3]
Hi,

I have cloned this code into a new repo and tried to generate gh-pages using the commands shared in the readme template. 

However, I am getting 404 errors for nuxt related files. 

<img width="1792" alt="image" src="https://github.com/lucpotage/nuxt-github-pages/assets/21080021/37aa78ed-8e24-4154-8cc1-fc0b7b138f85">

Tried with Node version - v16.19.1 & v18.15.0

Any help on this is appreciated.

**Comment by brignolij** [comment]
i'm facing the same issue, how did you solve it @SMNaik123 ?

**Comment by uwla** [comment]
Nuxt adds an underline prefix before the directory name of the generated assets and before the payload JSON. GitHub returns a 404  http  response to files whose name start with underline, therefore it  does  not  load script files built by nuxt. One solution is to rename  those  files  and any reference to them. Here is a bash script that fixes this:

```bash
!#/bin/bash

# switch to the directory the script is at
dir=$(dirname "$0")
cd "$dir" || exit 1

# remove _ prefix from nuxt build dir
mv _nuxt/ nuxt
find . -type f | xargs grep '/_nuxt' --files-with-matches | xargs sed 's;/_nuxt;/nuxt;g' -i

# remove _ prefix from JSON payload files
find . -type f -name '_payload.json' | while read f; do
  dir=$(dirname "$f")
  mv "$f" "${dir}/payload.json"
done
find . -type f | xargs grep 'payload.json' --files-with-matches | xargs sed 's;_payload.json;payload.json;g' -i
```
