### ISSUE TITLE
.nojekyll not copied

### ISSUE THREAD

**Issue by brignolij** [lucpotage/nuxt-github-pages#4]
Hello,
i'm using your tool and i appreciate it, thanks for your work.

To solve 404 issue, i had to add a empty file called .nojekyll at the root the repo.

So i added an empty file .nojekyll in the nuxt public folder. But when using your script with this deploy command :
`gh-pages -d .output/public`

the .nojekyll is skipped in the copy process from .output/public to the root in the branch gh-pages.

Is it normal ?

how can i fix ? maybe with parameters ?

Thanks in advance.

**Comment by lucpotage** [comment]
Hi @brignolij,

Sorry for the late notice but the [recent merge](https://github.com/lucpotage/nuxt-github-pages/pull/2) should fix your issue. My initial version indeed did not work for assets.
